"""Add unique constraints to quote tables

Revision ID: 00f8b321b75a
Revises: fff54c53729f
Create Date: 2026-04-02 18:49:10.618608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f8b321b75a'
down_revision: Union[str, Sequence[str], None] = 'fff54c53729f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_quote_1day_vfi_ts_date', ['vfi_time_series_id', 'q_date'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.drop_constraint('uq_quote_1day_vfi_ts_date', type_='unique')

    # ### end Alembic commands ###
