"""initial

Revision ID: 0c87021035dc
Revises: 
Create Date: 2026-03-28 16:07:23.959413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c87021035dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_code_2', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=45), nullable=True),
    sa.Column('subregion', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country')),
    sa.UniqueConstraint('iso_code_2', name=op.f('uq_country_iso_code_2')),
    sa.UniqueConstraint('name', name=op.f('uq_country_name'))
    )
    op.create_table('fit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fit'))
    )
    op.create_table('quoted_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quoted_unit'))
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sector')),
    sa.UniqueConstraint('name', name=op.f('uq_sector_name'))
    )
    op.create_table('timeframe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('is_intraday', sa.Boolean(), nullable=False),
    sa.Column('is_aggregatable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeframe')),
    sa.UniqueConstraint('code', name=op.f('uq_timeframe_code'))
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('allowed_time_series', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor'))
    )
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], name=op.f('fk_industry_sector_id_sector')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry')),
    sa.UniqueConstraint('name', name=op.f('uq_industry_name'))
    )
    op.create_table('quoted_unit_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quoted_unit_from_id', sa.Integer(), nullable=False),
    sa.Column('quoted_unit_to_id', sa.Integer(), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['quoted_unit_from_id'], ['quoted_unit.id'], name=op.f('fk_quoted_unit_conversion_quoted_unit_from_id_quoted_unit')),
    sa.ForeignKeyConstraint(['quoted_unit_to_id'], ['quoted_unit.id'], name=op.f('fk_quoted_unit_conversion_quoted_unit_to_id_quoted_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quoted_unit_conversion'))
    )
    op.create_table('gfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fit_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ticker_go', sa.String(length=45), nullable=True),
    sa.Column('ticker_bl', sa.String(length=45), nullable=True),
    sa.Column('ticker_yf', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_gfi_country_id_country')),
    sa.ForeignKeyConstraint(['fit_id'], ['fit.id'], name=op.f('fk_gfi_fit_id_fit')),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], name=op.f('fk_gfi_industry_id_industry')),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], name=op.f('fk_gfi_sector_id_sector')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gfi')),
    sa.UniqueConstraint('name', name=op.f('uq_gfi_name'))
    )
    op.create_table('currency_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], name=op.f('fk_currency_details_gfi_id_gfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency_details'))
    )
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('dividend_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['gfi.id'], name=op.f('fk_dividend_currency_id_gfi')),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], name=op.f('fk_dividend_gfi_id_gfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dividend'))
    )
    op.create_table('gfi_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=False),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_forward', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_forward', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('book_value_per_share', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('p_bv', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('last_dividend_amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_dividend_date', sa.Date(), nullable=True),
    sa.Column('week_52_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('week_52_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source_vendor', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], name=op.f('fk_gfi_fundamentals_gfi_id_gfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gfi_fundamentals')),
    sa.UniqueConstraint('gfi_id', name=op.f('uq_gfi_fundamentals_gfi_id'))
    )
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('mic', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('abbreviation', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['gfi.id'], name=op.f('fk_market_currency_id_gfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market'))
    )
    op.create_table('split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=False),
    sa.Column('split_date', sa.DateTime(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], name=op.f('fk_split_gfi_id_gfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_split'))
    )
    op.create_table('qfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('quoted_unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('quoted_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['gfi.id'], name=op.f('fk_qfi_currency_id_gfi')),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], name=op.f('fk_qfi_gfi_id_gfi')),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], name=op.f('fk_qfi_market_id_market')),
    sa.ForeignKeyConstraint(['quoted_unit_id'], ['quoted_unit.id'], name=op.f('fk_qfi_quoted_unit_id_quoted_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qfi')),
    sa.UniqueConstraint('name', name=op.f('uq_qfi_name'))
    )
    op.create_table('pips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qfi_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('pips_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['qfi_id'], ['qfi.id'], name=op.f('fk_pips_qfi_id_qfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pips'))
    )
    op.create_table('vfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qfi_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_ticker', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['qfi_id'], ['qfi.id'], name=op.f('fk_vfi_qfi_id_qfi')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_vfi_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vfi')),
    sa.UniqueConstraint('name', name=op.f('uq_vfi_name'))
    )
    op.create_table('vfi_time_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vfi_id', sa.Integer(), nullable=False),
    sa.Column('timeframe_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('history_days', sa.Integer(), nullable=True),
    sa.Column('last_imported_at', sa.DateTime(), nullable=True),
    sa.Column('last_imported_from', sa.Date(), nullable=True),
    sa.Column('last_imported_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframe.id'], name=op.f('fk_vfi_time_series_timeframe_id_timeframe')),
    sa.ForeignKeyConstraint(['vfi_id'], ['vfi.id'], name=op.f('fk_vfi_time_series_vfi_id_vfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vfi_time_series')),
    sa.UniqueConstraint('vfi_id', 'timeframe_id', name=op.f('uq_vfi_time_series_vfi_id'))
    )
    op.create_table('quote_1day',
    sa.Column('q_date', sa.Date(), nullable=False),
    sa.Column('vfi_time_series_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_time_series_id'], ['vfi_time_series.id'], name=op.f('fk_quote_1day_vfi_time_series_id_vfi_time_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_1day'))
    )
    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_1day_q_date'), ['q_date'], unique=False)

    op.create_table('quote_1hour',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vfi_time_series_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_time_series_id'], ['vfi_time_series.id'], name=op.f('fk_quote_1hour_vfi_time_series_id_vfi_time_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_1hour'))
    )
    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_1hour_timestamp'), ['timestamp'], unique=False)

    op.create_table('quote_1min',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vfi_time_series_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_time_series_id'], ['vfi_time_series.id'], name=op.f('fk_quote_1min_vfi_time_series_id_vfi_time_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_1min'))
    )
    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_1min_timestamp'), ['timestamp'], unique=False)

    op.create_table('quote_1month',
    sa.Column('q_date', sa.Date(), nullable=False),
    sa.Column('vfi_time_series_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_time_series_id'], ['vfi_time_series.id'], name=op.f('fk_quote_1month_vfi_time_series_id_vfi_time_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_1month'))
    )
    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_1month_q_date'), ['q_date'], unique=False)

    op.create_table('quote_1week',
    sa.Column('q_date', sa.Date(), nullable=False),
    sa.Column('vfi_time_series_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_time_series_id'], ['vfi_time_series.id'], name=op.f('fk_quote_1week_vfi_time_series_id_vfi_time_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_1week'))
    )
    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_1week_q_date'), ['q_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1week_q_date'))

    op.drop_table('quote_1week')
    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1month_q_date'))

    op.drop_table('quote_1month')
    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1min_timestamp'))

    op.drop_table('quote_1min')
    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1hour_timestamp'))

    op.drop_table('quote_1hour')
    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1day_q_date'))

    op.drop_table('quote_1day')
    op.drop_table('vfi_time_series')
    op.drop_table('vfi')
    op.drop_table('pips')
    op.drop_table('qfi')
    op.drop_table('split')
    op.drop_table('market')
    op.drop_table('gfi_fundamentals')
    op.drop_table('dividend')
    op.drop_table('currency_details')
    op.drop_table('gfi')
    op.drop_table('quoted_unit_conversion')
    op.drop_table('industry')
    op.drop_table('vendor')
    op.drop_table('timeframe')
    op.drop_table('sector')
    op.drop_table('quoted_unit')
    op.drop_table('fit')
    op.drop_table('country')
    # ### end Alembic commands ###
