"""SqlAlchemy 2.0, currency as CurrencyDetails of Gfi

Revision ID: 90b915deb5a4
Revises: ff2e17be9384
Create Date: 2026-03-06 16:39:19.605275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b915deb5a4'
down_revision: Union[str, Sequence[str], None] = 'ff2e17be9384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], name=op.f('fk_currency_details_gfi_id_gfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency_details'))
    )
    op.drop_table('currency')
    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dividend_date',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_dividend_currency_id_currency'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dividend_currency_id_gfi'), 'gfi', ['currency_id'], ['id'])

    with op.batch_alter_table('gfi', schema=None) as batch_op:
        batch_op.alter_column('fit_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('abbreviation',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_market_currency_id_currency'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_market_currency_id_gfi'), 'gfi', ['currency_id'], ['id'])

    with op.batch_alter_table('pips', schema=None) as batch_op:
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_from',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('price_precision',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pips_value',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)

    with op.batch_alter_table('qfi', schema=None) as batch_op:
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quoted_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quoted_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_qfi_currency_id_currency'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_qfi_currency_id_gfi'), 'gfi', ['currency_id'], ['id'])

    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_date', sa.Date(), nullable=False))
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1day_q_date'), ['q_date'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1hour_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1min_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_date', sa.Date(), nullable=False))
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1month_q_date'), ['q_date'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_date', sa.Date(), nullable=False))
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1week_q_date'), ['q_date'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('quoted_unit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)

    with op.batch_alter_table('quoted_unit_conversion', schema=None) as batch_op:
        batch_op.alter_column('quoted_unit_from_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quoted_unit_to_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('split_date',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('allowed_time_series',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)

    with op.batch_alter_table('vfi', schema=None) as batch_op:
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vfi', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('allowed_time_series',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.alter_column('split_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quoted_unit_conversion', schema=None) as batch_op:
        batch_op.alter_column('quoted_unit_to_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quoted_unit_from_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quoted_unit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quote_1week_q_date'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('q_date')

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quote_1month_q_date'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('q_date')

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1min_timestamp'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1hour_timestamp'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quote_1day_q_date'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('q_date')

    with op.batch_alter_table('qfi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_qfi_currency_id_gfi'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_qfi_currency_id_currency'), 'currency', ['currency_id'], ['id'])
        batch_op.alter_column('quoted_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quoted_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pips', schema=None) as batch_op:
        batch_op.alter_column('pips_value',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('price_precision',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_from',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_market_currency_id_gfi'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_market_currency_id_currency'), 'currency', ['currency_id'], ['id'])
        batch_op.alter_column('abbreviation',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('gfi', schema=None) as batch_op:
        batch_op.alter_column('fit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dividend_currency_id_gfi'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dividend_currency_id_currency'), 'currency', ['currency_id'], ['id'])
        batch_op.alter_column('dividend_date',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
        batch_op.alter_column('currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('currency',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gfi_id', sa.INTEGER(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=15), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('Numeric_places', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], name=op.f('fk_currency_gfi_id_gfi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency'))
    )
    op.drop_table('currency_details')
    # ### end Alembic commands ###
