"""added new fk dividends

Revision ID: b4bdb43fb709
Revises: 46ed47e4aafd
Create Date: 2026-03-06 18:04:21.870615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bdb43fb709'
down_revision: Union[str, Sequence[str], None] = '46ed47e4aafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gfi', schema=None) as batch_op:
        batch_op.alter_column('fit_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)

    with op.batch_alter_table('pips', schema=None) as batch_op:
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_from',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('price_precision',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pips_value',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)

    with op.batch_alter_table('qfi', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)

    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_date', sa.Date(), nullable=False))
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1day_q_date'), ['q_date'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1hour_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1min_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_date', sa.Date(), nullable=False))
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1month_q_date'), ['q_date'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_date', sa.Date(), nullable=False))
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_quote_1week_q_date'), ['q_date'], unique=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('quoted_unit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)

    with op.batch_alter_table('quoted_unit_conversion', schema=None) as batch_op:
        batch_op.alter_column('quoted_unit_from_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quoted_unit_to_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('split_date',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('allowed_time_series',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)

    with op.batch_alter_table('vfi', schema=None) as batch_op:
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vfi', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('allowed_time_series',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.alter_column('split_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
        batch_op.alter_column('gfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quoted_unit_conversion', schema=None) as batch_op:
        batch_op.alter_column('quoted_unit_to_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quoted_unit_from_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quoted_unit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quote_1week_q_date'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('q_date')

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quote_1month_q_date'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('q_date')

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1min_timestamp'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_1hour_timestamp'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quote_1day_q_date'))
        batch_op.alter_column('close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('vfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('q_date')

    with op.batch_alter_table('qfi', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)

    with op.batch_alter_table('pips', schema=None) as batch_op:
        batch_op.alter_column('pips_value',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
        batch_op.alter_column('price_precision',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_from',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('qfi_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)

    with op.batch_alter_table('gfi', schema=None) as batch_op:
        batch_op.alter_column('fit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
