"""Add unique constraints to dividend and split tables

Revision ID: c0040be9060b
Revises: 00f8b321b75a
Create Date: 2026-04-02 19:03:03.192505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0040be9060b'
down_revision: Union[str, Sequence[str], None] = '00f8b321b75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_dividend_entry', ['gfi_id', 'dividend_date', 'amount'])

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_quote_1hour_vfi_ts_timestamp', ['vfi_time_series_id', 'timestamp'])

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_quote_1min_vfi_ts_timestamp', ['vfi_time_series_id', 'timestamp'])

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_quote_1month_vfi_ts_date', ['vfi_time_series_id', 'q_date'])

    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_quote_1week_vfi_ts_date', ['vfi_time_series_id', 'q_date'])

    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_split_entry', ['gfi_id', 'split_date', 'ratio'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split', schema=None) as batch_op:
        batch_op.drop_constraint('uq_split_entry', type_='unique')

    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.drop_constraint('uq_quote_1week_vfi_ts_date', type_='unique')

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.drop_constraint('uq_quote_1month_vfi_ts_date', type_='unique')

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.drop_constraint('uq_quote_1min_vfi_ts_timestamp', type_='unique')

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.drop_constraint('uq_quote_1hour_vfi_ts_timestamp', type_='unique')

    with op.batch_alter_table('dividend', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dividend_entry', type_='unique')

    # ### end Alembic commands ###
