"""initial schema

Revision ID: cb0c6af3e3cf
Revises: 
Create Date: 2026-03-03 20:24:11.948363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0c6af3e3cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quoted_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('allowed_time_series', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('Numeric_places', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quoted_unit_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quoted_unit_from_id', sa.Integer(), nullable=True),
    sa.Column('quoted_unit_to_id', sa.Integer(), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['quoted_unit_from_id'], ['quoted_unit.id'], ),
    sa.ForeignKeyConstraint(['quoted_unit_to_id'], ['quoted_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=True),
    sa.Column('split_date', sa.String(length=45), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('dividend_date', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('abbreviation', sa.String(length=15), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfi_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('quoted_unit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('quoted_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['gfi_id'], ['gfi.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.ForeignKeyConstraint(['quoted_unit_id'], ['quoted_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qfi_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('pips_value', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['qfi_id'], ['qfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qfi_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('symbol', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['qfi_id'], ['qfi.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_1day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vfi_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_id'], ['vfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_1hour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vfi_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_id'], ['vfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_1min',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vfi_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_id'], ['vfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_1month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vfi_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_id'], ['vfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_1week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vfi_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vfi_id'], ['vfi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_1week')
    op.drop_table('quote_1month')
    op.drop_table('quote_1min')
    op.drop_table('quote_1hour')
    op.drop_table('quote_1day')
    op.drop_table('vfi')
    op.drop_table('pips')
    op.drop_table('qfi')
    op.drop_table('market')
    op.drop_table('dividend')
    op.drop_table('split')
    op.drop_table('quoted_unit_conversion')
    op.drop_table('currency')
    op.drop_table('vendor')
    op.drop_table('quoted_unit')
    op.drop_table('gfi')
    op.drop_table('fit')
    # ### end Alembic commands ###
