"""better precision for quotes

Revision ID: e6f14e747aab
Revises: cb0c6af3e3cf
Create Date: 2026-03-04 08:33:38.005557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f14e747aab'
down_revision: Union[str, Sequence[str], None] = 'cb0c6af3e3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pips', 'pips_value',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1week', 'open',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1week', 'high',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1week', 'low',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1week', 'close',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quote_1week', 'close',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1week', 'low',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1week', 'high',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1week', 'open',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'close',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'low',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'high',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1month', 'open',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'close',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'low',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'high',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1min', 'open',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'close',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'low',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'high',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1hour', 'open',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'close',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'low',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'high',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('quote_1day', 'open',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('pips', 'pips_value',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###
