"""added adj_close column-save

Revision ID: fff54c53729f
Revises: 9e3bdce8e3b8
Create Date: 2026-03-31 17:14:05.571086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff54c53729f'
down_revision: Union[str, Sequence[str], None] = '9e3bdce8e3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adj_close', sa.Numeric(precision=18, scale=8), nullable=True))

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adj_close', sa.Numeric(precision=18, scale=8), nullable=True))

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adj_close', sa.Numeric(precision=18, scale=8), nullable=True))

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adj_close', sa.Numeric(precision=18, scale=8), nullable=True))

    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adj_close', sa.Numeric(precision=18, scale=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_1week', schema=None) as batch_op:
        batch_op.drop_column('adj_close')

    with op.batch_alter_table('quote_1month', schema=None) as batch_op:
        batch_op.drop_column('adj_close')

    with op.batch_alter_table('quote_1min', schema=None) as batch_op:
        batch_op.drop_column('adj_close')

    with op.batch_alter_table('quote_1hour', schema=None) as batch_op:
        batch_op.drop_column('adj_close')

    with op.batch_alter_table('quote_1day', schema=None) as batch_op:
        batch_op.drop_column('adj_close')

    # ### end Alembic commands ###
