#!/bin/bash

# quick_start.sh - Quick start guide for yFinance data import
# This script demonstrates the complete workflow

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║          yFinance Data Import - Quick Start Guide              ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors for better readability
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${YELLOW}STEP 1: Ensure base reference data exists${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run the base seed script to create:"
echo "  - Financial Instrument Types (Shares, Bonds, etc.)"
echo "  - Currencies (PLN, USD, EUR, etc.)"
echo "  - Markets (Warsaw, NYSE, London, etc.)"
echo "  - Quoted Units (Shares, Bushels, etc.)"
echo ""
echo "Command:"
echo -e "  ${GREEN}python seed.py${NC}"
echo ""
read -p "Press Enter when seed.py has been run successfully..."
echo ""

echo -e "${YELLOW}STEP 2: Prepare your ticker list${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Create a text file with one ticker per line."
echo ""
echo "Example (tickers_warsaw.txt):"
echo "  11B.WA"
echo "  PKO.WA"
echo "  CDR.WA"
echo ""
echo "Example files provided:"
echo "  - example_tickers_warsaw.txt (Polish stocks)"
echo "  - example_tickers_us.txt (US stocks)"
echo ""
read -p "Press Enter when you have your ticker list ready..."
echo ""

echo -e "${YELLOW}STEP 3: Fetch data from yFinance${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Use the fetch script to download data from yFinance API."
echo ""
echo "Command:"
echo -e "  ${GREEN}python fetch_yfinance_data.py example_tickers_warsaw.txt data/warsaw_stocks.json${NC}"
echo ""
echo "This will:"
echo "  - Fetch data for each ticker from yFinance"
echo "  - Save results to JSON file"
echo "  - Display summary statistics"
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${YELLOW}STEP 4: Validate your JSON data${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Before importing, validate the data quality."
echo ""
echo "Command:"
echo -e "  ${GREEN}python validate_yfinance_json.py data/warsaw_stocks.json${NC}"
echo ""
echo "The validator checks for:"
echo "  ✓ Required fields present"
echo "  ✓ Data types correct"
echo "  ⚠ Missing recommended fields"
echo "  ℹ Fundamentals coverage"
echo ""
echo "Fix any issues before proceeding to import."
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${YELLOW}STEP 5: Import data into database${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Import validated data into your database."
echo ""
echo "Command:"
echo -e "  ${GREEN}python seed_yfinance.py data/${NC}"
echo ""
echo "This will:"
echo "  - Create/update Gfi (Global Financial Instruments)"
echo "  - Create/update GfiFundamentals"
echo "  - Create Qfi (Quoted Financial Instruments)"
echo "  - Create reference data (Country, Sector, Industry)"
echo ""
echo "The import is IDEMPOTENT - safe to run multiple times."
echo ""
read -p "Press Enter to continue..."
echo ""

echo -e "${YELLOW}STEP 6: Verify import${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Check your database to verify the import was successful."
echo ""
echo "Example SQL queries:"
echo ""
echo "-- Count imported instruments"
echo "SELECT COUNT(*) FROM gfi WHERE ticker_yf IS NOT NULL;"
echo ""
echo "-- View imported stocks with fundamentals"
echo "SELECT g.name, g.ticker_yf, f.market_cap, f.pe"
echo "FROM gfi g"
echo "JOIN gfi_fundamentals f ON g.id = f.gfi_id"
echo "WHERE g.ticker_yf IS NOT NULL;"
echo ""
echo "-- View quoted instruments by market"
echo "SELECT q.name, m.abbreviation, q.quoted_amount"
echo "FROM qfi q"
echo "JOIN market m ON q.market_id = m.id;"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║                      🎉 Setup Complete! 🎉                     ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo -e "${GREEN}Your database is now populated with yFinance data!${NC}"
echo ""
echo "Next steps:"
echo "  1. Import historical price data (Quote_1day tables)"
echo "  2. Set up data vendors (Vfi records)"
echo "  3. Configure time series collection (VfiTimeSeries)"
echo "  4. Schedule regular updates for fundamentals"
echo ""
echo "For detailed documentation, see:"
echo "  - YFINANCE_IMPORT_GUIDE.md"
echo ""
echo "Useful commands:"
echo -e "  ${GREEN}python validate_yfinance_json.py <file_or_dir>${NC}  - Validate data"
echo -e "  ${GREEN}python seed_yfinance.py <json_directory>${NC}       - Import data"
echo -e "  ${GREEN}python fetch_yfinance_data.py <tickers> <output>${NC} - Fetch new data"
echo ""
